# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

button: !include button.yaml

input_datetime:
  alarm_time:
    name: Alarm Time
    has_time: true
    has_date: false

lovelace:
  mode: yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.17.0.0/16
    - 172.16.0.0/12